server:
  port: 8085
  
spring:
  application:
    name: CLOUD-CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rishabhsharma5554/RatingMicroservicesCloudConfig
          clone-on-start: true
          

    
