server:
  port: 8082
spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: RatingMicroserviceDB
  config:
    import: configserver:http://localhost:8085
    
#comming from config server
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
      